### ISSUE TITLE
it's not counting white spaces! wtf?!

### ISSUE THREAD

**Issue by cauerego** [ystkme/count-word#2]
I just opened a new document, pasted this below and it counted to 3, ignoring the white space!

`12 3`

**Comment by yo7** [comment]
It's expected behavior. This plugin counts characters ignoring white spaces.

**Comment by cauerego** [comment]
Couldn't you at least count both? ;)

**Comment by yo7** [comment]
It's not difficult to change its behavior to count whitespaces. But I wouldn' t do that myself because I don't use Atom now.

Of course you can fork thin repo and make some changes. Or write the plugin you want by yourself.
It's kind of easy. There's a [official tutorial](https://atom.io/docs/latest/hacking-atom-package-word-count) to create the plugin to count words.  I made this based on the tutorial to study how to make Atom plugins.

**Comment by cauerego** [comment]
I was just waiting for that answer... So, sublime, huh? ;P

I'd move there too, but too lazy even for that.

**Comment by yo7** [comment]
Nope. Now I use vim. I can write code and execute commands inside terminal and it's comfortble. But Atom and Sublime are good editors in different ways.

Hope you find great editor and plugins... Good luck!
